
persistence:
  # Enable or disable persistence
  enabled: true
  # Access mode for the persistent volume claim
  accessMode: ReadWriteOnce
  # Size of the persistent volume claim
  size: 5Gi
  # Storage class for the persistent volume claim
  storageClass: "longhorn"