
# traefik

- name: "Traefik: Add helm chart repo"
  kubernetes.core.helm_repository:
    name: traefik
    repo_url: "https://traefik.github.io/charts"

- name: "Traefik: Deploy with values loaded from template"
  kubernetes.core.helm:
    name: "{{ traefik_release }}"
    create_namespace: true
    chart_ref: traefik/traefik
    release_namespace: "{{ traefik_namespace }}"
    chart_version: "{{ traefik_version }}"
    values: "{{ lookup('template', 'traefik-values.yml') | from_yaml }}"

# longhorn

- name: "Longhorn: Add helm chart repo"
  kubernetes.core.helm_repository:
    name: longhorn
    repo_url: "https://charts.longhorn.io"

- name: "Longhorn: Deploy with values loaded from template"
  kubernetes.core.helm:
    name: "{{ longhorn_release }}"
    create_namespace: true
    chart_ref: longhorn/longhorn
    release_namespace: "{{ longhorn_namespace }}"
    chart_version: "{{ longhorn_version }}"
    values: "{{ lookup('template', 'longhorn-values.yml') | from_yaml }}"

# cert-manager

- name: "cert-manager: Add helm chart repo"
  kubernetes.core.helm_repository:
    name: cert-manager
    repo_url: "https://charts.jetstack.io"

- name: "cert-manager: Deploy with values loaded from template"
  kubernetes.core.helm:
    name: "{{ certmanager_release }}"
    create_namespace: true
    chart_ref: cert-manager/cert-manager
    release_namespace: "{{ certmanager_namespace }}"
    chart_version: "{{ certmanager_version }}"
    values: "{{ lookup('template', 'certmanager-values.yml') | from_yaml }}"

- name: "cert-manager: Create Issuer"
  kubernetes.core.k8s:
    state: present
    template: 'certmanager-issuer.yml.j2'

# keycloak

- name: "keycloak: Add helm chart repo"
  kubernetes.core.helm_repository:
    name: bitnami 
    repo_url: "https://charts.bitnami.com/bitnami"

- name: "keycloak: Deploy with values loaded from template"
  kubernetes.core.helm:
    name: "{{ keycloak_release }}"
    create_namespace: true
    chart_ref: bitnami/keycloak
    release_namespace: "{{ keycloak_namespace }}"
    chart_version: "{{ keycloak_version }}"
    values: "{{ lookup('template', 'keycloak-values.yml') | from_yaml }}"

- name: "cert-manager: Create Issuer"
  kubernetes.core.k8s:
    state: present
    template: 'keycloak-ingress.yml.j2'
