- name: Load existing Netplan config
  slurp:
    src: /etc/netplan/50-cloud-init.yaml
  register: netplan_raw

- name: Parse YAML content
  set_fact:
    netplan_config: "{{ netplan_raw.content | b64decode | from_yaml }}"

- name: Check if IPv6 address already exists
  set_fact:
    ipv6_already_present: "{{ ipv6_wg_mesh_net in netplan_config.network.ethernets.eth0.addresses }}"

- name: Ensure new IPv6 address is present
  set_fact:
    netplan_config: >-
      {{
        netplan_config | combine({
          'network': {
            'ethernets': {
              'eth0': {
                'addresses': (
                  netplan_config.network.ethernets.eth0.addresses | union([ipv6_wg_mesh_net])
                )
              }
            }
          }
        }, recursive=True)
      }}
  when: not ipv6_already_present

- name: Write updated Netplan config
  copy:
    dest: /etc/netplan/50-cloud-init.yaml
    content: "{{ netplan_config | to_nice_yaml(indent=2) }}"
  register: netplan_result
  when: not ipv6_already_present

- name: Apply Netplan
  command: netplan apply
  when: netplan_result.changed