# Kubernetes Core
# kube_version: 1.33.3
kube_network_plugin: calico
etcd_deployment_type: kubeadm
dns_mode: coredns
cluster_name: hcloud1.k8s.gamma.red

# Load Balancer
loadbalancer_apiserver_localhost: true
# loadbalancer_apiserver_type: haproxy

# kube_apiserver_bind_address: "10.0.1.5"
# loadbalancer_apiserver:
#   address: 10.0.1.5  # Ihre VIP
#   port: 6443
# supplementary_addresses_in_ssl_keys:
#   - 10.0.1.5  # VIP f端r externes kubectl

## testen=
# loadbalancer_apiserver_localhost: true
# loadbalancer_apiserver_type: haproxy
# loadbalancer_apiserver:
#   address: 10.0.1.4  # VIP
#   port: 6443
# kube_apiserver_bind_address: "0.0.0.0"


# DNS Optimierung
enable_nodelocaldns: true

# Netzwerk
kube_service_addresses: 10.233.0.0/18
kube_pods_subnet: 10.233.64.0/18
kube_proxy_mode: ipvs
kube_proxy_strict_arp: true

# Container Runtime
container_manager: containerd

# Security
podsecuritypolicy_enabled: false
kubelet_authentication_token_webhook: true
kubelet_authorization_mode_webhook: true

# Backup
etcd_backup_enabled: true
etcd_backup_schedule: "0 2 * * *"

# Kubernetes Dashboard (optional)
dashboard_enabled: false  # Security-Risk, besser externe Tools

# Metrics Server (empfohlen)
metrics_server_enabled: true

# Lokaler Registry Mirror (optional f端r bessere Performance)
registry_enabled: false

# MetalLB Installation f端r LoadBalancer-Services
metallb_enabled: false # true
metallb_speaker_enabled: false # true
# metallb_namespace: metallb-system
# metallb_protocol: "layer2"
# metallb_config:
#   address_pools:
#     primary:
#       ip_range:
#         - 10.0.1.100-10.0.1.200
#       protocol: layer2


# metallb_config:
#   address_pools:
#     primary:
#       ip_range:
#         - 10.0.1.100-10.0.1.200
#       protocol: layer2



# metallb_enabled: true
# metallb_speaker_enabled: true
# metallb_namespace: metallb-system
# metallb_protocol: bgp

# metallb_config:
#   peers:
#     - peer_address: 10.0.1.2  # Unser virtueller Router
#       peer_asn: 65001
#       my_asn: 65002
#       source_address: 10.0.1.6  # IP deiner ersten Node
#   address_pools:
#     primary:
#       ip_range:
#         - 10.0.2.100-10.0.2.200
#       protocol: bgp
#       auto_assign: true

###

# # Calico BGP aktivieren
calico_bgp_enabled: true
# calico_rr_enabled: false  # Erstmal ohne Route Reflector
calico_node_mesh_enabled: true

# # BGP AS Number
# calico_as_number: 64512  # Deine AS-Nummer

# # Calico IPIP deaktivieren f端r native BGP
calico_network_backend: bird

#00:24
calico_ipip_mode: 'Never'
calico_vxlan_mode: 'Never'
# calico_advertise_cluster_ips: true
# calico_additional_static_routes:
#   - cidr: "192.168.0.0/22"
#     gateway: "blackhole"
#     node_selector: "kubernetes.io/hostname == 'node02'"


# # Optional: Specific Node-zu-Node BGP
calico_node_to_node_mesh: true