# Clustername
cluster_name: hcloud1.k8s.gamma.red

# Netzwerk-Settings
kube_pods_subnet: 10.233.64.0/18
kube_service_addresses: 10.233.0.0/18
kube_proxy_mode: ipvs
kube_proxy_strict_arp: true

# DNS
dns_mode: coredns
enable_nodelocaldns: true

# Container Runtime
container_manager: containerd

# Etcd
etcd_deployment_type: kubeadm
etcd_backup_enabled: true
etcd_backup_schedule: "0 2 * * *"

# Security
podsecuritypolicy_enabled: false
kubelet_authentication_token_webhook: true
kubelet_authorization_mode_webhook: true

# Monitoring
metrics_server_enabled: true

# LoadBalancer via Cilium
loadbalancer_apiserver_localhost: true

# Dashboard
dashboard_enabled: false

## Calico ##
kube_network_plugin: calico
calico_backend: vxlan # bird

# IP-in-IP deaktivieren (nutzen VXLAN stattdessen)
calico_ipip_mode: 'Never'
calico_vxlan_mode: 'Always'

# # Network Policy Engine
# calico_network_policy: true

# # Felix Konfiguration
# calico_felix_log_level: "Info"
# calico_felix_prometheusmetricsenabled: true
# calico_felix_prometheusmetricsport: 9091


# # MTU Settings (wichtig f端r VXLAN)
# calico_mtu: 1450  # Standard f端r VXLAN overhead


## Cilium ##
# kube_network_plugin: cilium

# # Cilium ohne Overlay, nutzt WireGuard-Netz direkt
# cilium_tunnel_mode: "disabled"

# # eBPF-KubeProxy ersetzen f端r Performance
# cilium_kube_proxy_replacement: true #"strict"

# # Node-to-Node Routing (da WG)
# cilium_auto_direct_node_routes: true

# # Transparent LoadBalancer 端ber Cilium
# cilium_native_routing_cidr: "10.0.1.0/24"

# # Metrics und Debug
# cilium_enable_prometheus: true
# cilium_enable_bandwidth_manager: true
# cilium_enable_hubble: true

# # systemd kompatible cgroup hierarchie
# #cilium_cgroup_mode: "legacy"
# kubelet_cgroup_driver: systemd
# cilium_cgroup_auto_mount: false
# cilium_enable_ipv4: true
# cilium_enable_ipv6: true
# cilium_preallocate_bpf_maps: false

# kubelet_config_extra_args:
#   cgroupDriver: systemd
#   cgroupRoot: /