# Clustername
cluster_name: hcloud1.k8s.gamma.red

# Enable HELM and argo
helm_enabled: true
# argocd_enabled: true # Installation later via helm

# Netzwerk-Settings
kube_pods_subnet: 10.233.64.0/18
kube_service_addresses: 10.233.0.0/18
kube_proxy_mode: ipvs
kube_proxy_strict_arp: true

# 03.08
# enable_dual_stack_networks: true # deprecated
kube_pods_subnet_ipv6: fd85:ee78:d8a6:8607::1:0000/112
kube_service_addresses_ipv6: fd85:ee78:d8a6:8607::1000/116
# kube_network_node_prefix_ipv6: 120

ipv4_stack: true
ipv6_stack: true

# DNS
dns_mode: coredns
enable_nodelocaldns: true

# Container Runtime
container_manager: containerd

# Etcd
etcd_deployment_type: kubeadm
etcd_backup_enabled: true
etcd_backup_schedule: "0 2 * * *"

# Security
podsecuritypolicy_enabled: false
kubelet_authentication_token_webhook: true
kubelet_authorization_mode_webhook: true

# Monitoring
metrics_server_enabled: true

# LoadBalancer via Cilium
loadbalancer_apiserver_localhost: true

# Dashboard
dashboard_enabled: false

## Calico ##
kube_network_plugin: calico
calico_backend: vxlan # bird

# IP-in-IP deaktivieren (nutzen VXLAN stattdessen)
calico_ipip_mode: 'Never'
calico_vxlan_mode: 'Always'

# # Network Policy Engine
# calico_network_policy: true

# # Felix Konfiguration
# calico_felix_log_level: "Info"
# calico_felix_prometheusmetricsenabled: true
# calico_felix_prometheusmetricsport: 9091


# # MTU Settings (wichtig für VXLAN)
# calico_mtu: 1450  # Standard für VXLAN overhead

